# Generated by Django 4.0 on 2023-06-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messaage',
            old_name='meesage',
            new_name='meessage',
        ),
    ]
