# Generated by Django 4.0 on 2023-06-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_meessage_messaage_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messaage',
            old_name='message',
            new_name='content',
        ),
    ]
